### ISSUE TITLE
We should be utilizing Composer

### ISSUE THREAD

**Issue by ebbesmoeller** [onpayio/whmcs#1]
Consider utilizing Composer for OnPay SDK dependencies.
This will make it far easier to upgrade the PHP-SDK and other dependencies down the line.

**Comment by lucasRolff** [comment]
Composer is already in use: https://github.com/onpayio/whmcs/blob/master/onpay/composer.json - the `vendor` folder is simply stored in the `onpay` directory, since that's the only isolated directory in use for any module files.

**Comment by ebbesmoeller** [comment]
Ah, cool. :-)
All dependencies (files) is included in the repository though. I think that we should remove these files, since they are not needed, and preserve only the composer lock/json files. Perhaps we should add a build script for the plugin, and utilize the 'Releases' part of Github.

**Comment by ebbesmoeller** [comment]
We'll look into doing this. :-)

**Comment by ebbesmoeller** [comment]
Proposed fix: https://github.com/onpayio/whmcs/pull/2

**Comment by ebbesmoeller** [comment]
Resolved #2
